name: Deploy React App to EC2 and Create Release

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies and build React app
        run: |
          npm install
          npm run build

      - name: SSH into EC2 server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            cd /var/www/html
            rm -rf *
            exit

      - name: Copy build files to EC2 server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.EC2_SSH_PORT }}
          source: dist/
          target: /var/www/html/

      - name: Restart Nginx on EC2 server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            sudo systemctl restart nginx

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes